export type Tool = {
  name: string;
  desc: string;
  usage?: string;
  deps?: string;
};

export type Category = {
  id: string;
  index: string;
  name: string;
  sigil: string;
  blurb: string;
  tools: Tool[];
};

export const CATEGORIES: Category[] = [
  {
    id: "files",
    index: "01",
    name: "NAVIGATION & FILES",
    sigil: "~/",
    blurb: "Move through a filesystem like you own it. Find, size, compress, clipboard, restore.",
    tools: [
      { name: "mkcd", desc: "make a directory and cd into it in one step", usage: "mkcd <dir>" },
      { name: "up", desc: "go up N directory levels", usage: "up [n]" },
      { name: "lsd", desc: "beautiful directory listing with git status", usage: "lsd [path]", deps: "eza" },
      { name: "fcd", desc: "fuzzy-pick a subdirectory and cd into it", usage: "fcd", deps: "fzf" },
      { name: "ftext", desc: "fuzzy-search file contents, open match in $EDITOR", usage: "ftext", deps: "fzf" },
      { name: "permsof", desc: "show file permissions broken down by owner/group/other", usage: "permsof <file>" },
      { name: "extract", desc: "auto-extract any archive by extension", usage: "extract <archive-file>" },
      { name: "compress", desc: "tar.gz, tar.bz2 or zip a file or directory", usage: "compress <out.zip|tar.gz> <path>" },
      { name: "duh", desc: "disk usage here, sorted by size", usage: "duh" },
      { name: "sizeof", desc: "sizes of subdirectories, largest first", usage: "sizeof [path]" },
      { name: "findbig", desc: "find files above a size threshold", usage: "findbig [size] [dir]" },
      { name: "emptydirs", desc: "locate and prune empty directories", usage: "emptydirs [dir]" },
      { name: "dupfind", desc: "find duplicate files by SHA-256 hash", usage: "dupfind [dir]" },
      { name: "bak", desc: "timestamped backup copy of a file", usage: "bak <file>" },
      { name: "cwd", desc: "copy working directory path to clipboard", usage: "cwd" },
      { name: "clipcopy", desc: "copy file contents to clipboard", usage: "clipcopy <file>" },
      { name: "clip", desc: "copy stdin or a file to the clipboard, pipe-friendly", usage: "clip [file]" },
      { name: "watchrun", desc: "re-run a command whenever a path changes", usage: "watchrun <path> -- <cmd>", deps: "entr, fswatch" },
      { name: "treelist", desc: "recursive tree listing with pure shell fallback", usage: "treelist [dir] [depth]" },
      { name: "recent", desc: "most recently modified files in directory tree", usage: "recent [n]" },
      { name: "swap", desc: "atomically swap two filenames via temp file", usage: "swap <file-a> <file-b>" },
      { name: "trash", desc: "move a path to system trash safely", usage: "trash <file-or-dir>" },
    ],
  },
  {
    id: "git",
    index: "02",
    name: "GIT",
    sigil: "⌥",
    blurb: "Undo, prune, checkpoint, inspect, open PRs. The commands you retype every single day.",
    tools: [
      { name: "gitundo", desc: "undo the last commit, keep changes staged", usage: "gitundo" },
      { name: "branchclean", desc: "delete branches already merged into main", usage: "branchclean" },
      { name: "branchage", desc: "local branches sorted by last activity", usage: "branchage" },
      { name: "gitlog-today", desc: "today's commits authored by you since midnight", usage: "gitlog-today" },
      { name: "gacp", desc: "add + commit + push, guarded on main", usage: "gacp <commit message>" },
      { name: "gclone", desc: "clone a repository and cd straight into it", usage: "gclone <repo-url> [dir]" },
      { name: "gwip", desc: "checkpoint commit for uncommitted work", usage: "gwip" },
      { name: "gunwip", desc: "roll the checkpoint back, staged", usage: "gunwip" },
      { name: "gitprune", desc: "drop tracking branches whose remote is gone", usage: "gitprune" },
      { name: "gswitch", desc: "fuzzy branch switcher, local + remote", usage: "gswitch", deps: "fzf" },
      { name: "prdiff", desc: "diff the current branch against base", usage: "prdiff [base-branch]" },
      { name: "gitcontributors", desc: "commit counts per author", usage: "gitcontributors" },
      { name: "gitsize", desc: "total size of the .git directory", usage: "gitsize" },
      { name: "gitconflicts", desc: "list files with unresolved conflicts", usage: "gitconflicts" },
      { name: "gitignore", desc: "fetch and append gitignore.io templates", usage: "gitignore <langs...>" },
      { name: "gstash", desc: "interactive stash picker (pop, apply, drop)", usage: "gstash", deps: "fzf" },
      { name: "grebase", desc: "interactive rebase N commits back", usage: "grebase [n]" },
      { name: "gopen", desc: "open origin repo URL in browser", usage: "gopen" },
      { name: "gpr", desc: "open PR creation page for the current branch", usage: "gpr" },
      { name: "gcamend", desc: "amend the last commit with a new message", usage: "gcamend <new message>" },
      { name: "gdiffstage", desc: "show what is currently staged (git diff --cached)", usage: "gdiffstage" },
      { name: "grecentbranch", desc: "recently checked-out branches from reflog", usage: "grecentbranch [n]" },
      { name: "gitbranch-rename", desc: "rename branch locally and on remote", usage: "gitbranch-rename <old> <new>" },
      { name: "gitlog-graph", desc: "pretty one-line graph log with colors", usage: "gitlog-graph" },
      { name: "gcleanup", desc: "prune remotes, delete merged branches, tidy module", usage: "gcleanup" },
    ],
  },
  {
    id: "docker",
    index: "03",
    name: "DOCKER",
    sigil: "▣",
    blurb: "Container triage and lifecycle management without memorising four flags per command.",
    tools: [
      { name: "dockernuke", desc: "force stop and remove a container", usage: "dockernuke <container>" },
      { name: "dockerclean-images", desc: "remove dangling Docker images", usage: "dockerclean-images" },
      { name: "dclean", desc: "reclaim all unused docker data", usage: "dclean" },
      { name: "dockerlogs", desc: "tail container logs with timestamps", usage: "dockerlogs <container>" },
      { name: "dsh", desc: "fuzzy-pick a container, drop into a shell", usage: "dsh", deps: "fzf" },
      { name: "dockersizes", desc: "human-readable local image sizes", usage: "dockersizes" },
      { name: "denv", desc: "print all environment variables of a container", usage: "denv <container>" },
      { name: "dbuild", desc: "build image tagged from current directory name", usage: "dbuild [tag]" },
    ],
  },
  {
    id: "k8s",
    index: "04",
    name: "KUBERNETES",
    sigil: "☸",
    blurb: "Context switching, pod ops, log streaming, and port-forwarding in one verb each.",
    tools: [
      { name: "k8sctx", desc: "fuzzy-switch context and namespace", usage: "k8sctx", deps: "fzf, kubectl" },
      { name: "klogs", desc: "fuzzy-pick a pod, stream its logs", usage: "klogs", deps: "fzf, kubectl" },
      { name: "kexec", desc: "fuzzy-pick a pod, exec a shell", usage: "kexec", deps: "fzf, kubectl" },
      { name: "ktop", desc: "pods by CPU / memory pressure", usage: "ktop [cpu|memory]", deps: "kubectl" },
      { name: "kevents", desc: "namespace events, most recent last", usage: "kevents", deps: "kubectl" },
      { name: "kns", desc: "switch kubectl namespace quickly", usage: "kns <namespace>", deps: "kubectl" },
      { name: "kdesc", desc: "fuzzy-pick a pod and describe it", usage: "kdesc", deps: "fzf, kubectl" },
      { name: "kport", desc: "port-forward local port to a pod", usage: "kport <local-port> <pod> <remote-port>", deps: "kubectl" },
    ],
  },
  {
    id: "go",
    index: "05",
    name: "GO",
    sigil: "{}",
    blurb: "Go project chores collapsed into one verb each. Coverage, benchmarks, scaffolding.",
    tools: [
      { name: "covreport", desc: "go test with coverage, opens HTML report", usage: "covreport" },
      { name: "gomodwhy", desc: "explain why a module is in the graph", usage: "gomodwhy <module-path>" },
      { name: "goclean", desc: "tidy, vet and format in one pass", usage: "goclean" },
      { name: "goupdate", desc: "upgrade Go dependencies to latest versions", usage: "goupdate" },
      { name: "gobench", desc: "benchmarks with memory stats", usage: "gobench [pattern]" },
      { name: "gonew", desc: "scaffold a minimal new Go module", usage: "gonew <module-path>" },
      { name: "gowatch", desc: "re-run Go tests on file save", usage: "gowatch", deps: "entr" },
    ],
  },
  {
    id: "node",
    index: "06",
    name: "NODE / NPM",
    sigil: "▸",
    blurb: "npm/yarn/pnpm chores in one word. Clean, scripts, outdated, size.",
    tools: [
      { name: "npmclean", desc: "nuke node_modules + lockfile, reinstall (auto-detects npm/yarn/pnpm)", usage: "npmclean" },
      { name: "npmscripts", desc: "list scripts defined in package.json", usage: "npmscripts", deps: "jq" },
      { name: "npmoutdated", desc: "outdated deps, compact form", usage: "npmoutdated" },
      { name: "npmsize", desc: "print total size of node_modules", usage: "npmsize" },
    ],
  },
  {
    id: "python",
    index: "07",
    name: "PYTHON",
    sigil: "🐍",
    blurb: "Virtual environments, cache cleanup, and requirements pinning in seconds.",
    tools: [
      { name: "venvcreate", desc: "create and activate ./venv", usage: "venvcreate" },
      { name: "pyclean", desc: "remove __pycache__ and .pyc recursively", usage: "pyclean" },
      { name: "pyfreeze", desc: "freeze packages into requirements.txt", usage: "pyfreeze" },
    ],
  },
  {
    id: "net",
    index: "08",
    name: "NETWORKING & APIS",
    sigil: "◇",
    blurb: "Is it me, DNS, the cert, or the port? Answer in one line.",
    tools: [
      { name: "myip", desc: "public-facing IP address", usage: "myip" },
      { name: "localip", desc: "local network IP address", usage: "localip" },
      { name: "killport", desc: "kill whatever is squatting on a port", usage: "killport <port> [port...]" },
      { name: "portwho", desc: "which process is listening on a port", usage: "portwho <port>" },
      { name: "openports", desc: "list listening ports, flagged if exposed to 0.0.0.0/::", usage: "openports" },
      { name: "portscan", desc: "TCP connect-scan a port range on a remote host", usage: "portscan <host> <start> [end]" },
      { name: "certcheck", desc: "TLS expiry date and days remaining", usage: "certcheck <domain>" },
      { name: "tlscheck", desc: "print full TLS certificate chain (subject, issuer, SANs)", usage: "tlscheck <domain> [port]" },
      { name: "dnscheck", desc: "A, CNAME and MX records for a domain", usage: "dnscheck <domain>" },
      { name: "ipinfo", desc: "IP geolocation, ASN and org via ipinfo.io", usage: "ipinfo [ip]" },
      { name: "httpstatus", desc: "status code plus what it actually means", usage: "httpstatus <url>" },
      { name: "apihit", desc: "curl with pretty JSON, timing and status", usage: "apihit <url> [curl-args...]" },
      { name: "headers", desc: "show full HTTP response headers", usage: "headers <url>" },
      { name: "flushdns", desc: "flush the local DNS cache", usage: "flushdns" },
      { name: "tcpcheck", desc: "raw TCP reachability on host:port", usage: "tcpcheck <host> <port>" },
      { name: "pingcheck", desc: "send 5 pings with latency/loss summary", usage: "pingcheck <host>" },
      { name: "weather", desc: "weather via wttr.in in terminal", usage: "weather [location]" },
      { name: "shorten", desc: "shorten a URL via is.gd", usage: "shorten <url>" },
      { name: "sshconfig", desc: "list all hosts configured in ~/.ssh/config", usage: "sshconfig" },
      { name: "proxy", desc: "toggle http(s)_proxy env vars on/off/status", usage: "proxy <on|off|status>" },
    ],
  },
  {
    id: "security",
    index: "09",
    name: "SECURITY & ENCODING",
    sigil: "✱",
    blurb: "Keys, hashes, encodings, and JWTs. No browser tab required.",
    tools: [
      { name: "passgen", desc: "random base64 password", usage: "passgen [bytes]" },
      { name: "pubkey", desc: "print your SSH public keys", usage: "pubkey" },
      { name: "genssh", desc: "new ed25519 keypair", usage: "genssh <key-name> [email]" },
      { name: "b64e", desc: "base64 encode text", usage: "b64e <text>" },
      { name: "b64d", desc: "base64 decode text", usage: "b64d <base64-text>" },
      { name: "urlencode", desc: "URL encode text", usage: "urlencode <text>" },
      { name: "urldecode", desc: "URL decode text", usage: "urldecode <text>" },
      { name: "hashfile", desc: "MD5, SHA1 and SHA256 of a file", usage: "hashfile <file>" },
      { name: "genuuid", desc: "random UUID v4", usage: "genuuid" },
      { name: "jwtdecode", desc: "decode JWT header and payload to JSON", usage: "jwtdecode <token>", deps: "jq" },
      { name: "dotenv-check", desc: "lint .env file for secrets, unquoted vars and duplicates", usage: "dotenv-check [file]" },
    ],
  },
  {
    id: "system",
    index: "10",
    name: "SYSTEM & PROCESS",
    sigil: "▤",
    blurb: "Processes, resources, memory, timers, and listening ports.",
    tools: [
      { name: "mem", desc: "current physical memory usage", usage: "mem" },
      { name: "cpu", desc: "snapshot of CPU / process activity", usage: "cpu" },
      { name: "sysinfo", desc: "one-screen OS, CPU, RAM, disk, uptime summary", usage: "sysinfo" },
      { name: "pidtree", desc: "process tree for a PID", usage: "pidtree <pid>" },
      { name: "fkill", desc: "fuzzy-pick a process and kill it", usage: "fkill", deps: "fzf" },
      { name: "now", desc: "current date and time (YYYY-MM-DD HH:MM:SS)", usage: "now" },
      { name: "timer", desc: "countdown with terminal audio/bell", usage: "timer <seconds> [label]" },
      { name: "diskusage", desc: "interactive disk usage via ncdu or df/du", usage: "diskusage [path]", deps: "ncdu" },
      { name: "envdiff", desc: "diff two .env files by key=value pairs", usage: "envdiff <file1> <file2>" },
      { name: "ports", desc: "list listening TCP/UDP ports with PID/process", usage: "ports" },
    ],
  },
  {
    id: "prod",
    index: "11",
    name: "PRODUCTIVITY & WORKFLOW",
    sigil: "⚡",
    blurb: "Notes, todos, history search, JSON diffing, project scaffolding, and retries.",
    tools: [
      { name: "note", desc: "append a timestamped line to ~/notes; subcommands: today, list, search", usage: "note <text|today|list|search <text>>" },
      { name: "todo", desc: "append or list entries in ~/todo.md; mark done with todo done <pattern>", usage: "todo [text]" },
      { name: "hist", desc: "fuzzy-search shell history and paste selection", usage: "hist", deps: "fzf" },
      { name: "mkproject", desc: "scaffold Go, Node, or Python project with git", usage: "mkproject <name> [go|node|python]" },
      { name: "mktemplate", desc: "create a new project from a custom template in ~/.sharmory/templates/", usage: "mktemplate <template> <project>" },
      { name: "envload", desc: "load a .env into the current shell", usage: "envload [file]" },
      { name: "envswitch", desc: "load a named env profile from ~/.sharmory/envprofiles/", usage: "envswitch [profile-name]" },
      { name: "ffind", desc: "find files by name or search text contents", usage: "ffind <text> | ffind -f <name>" },
      { name: "cheat", desc: "tldr with a man-page fallback", usage: "cheat <command>", deps: "tldr" },
      { name: "calc", desc: "arithmetic without leaving prompt", usage: "calc <expression>" },
      { name: "qr", desc: "QR code straight into the terminal", usage: "qr <text>" },
      { name: "jsonpp", desc: "pretty-print a JSON file", usage: "jsonpp <file>", deps: "jq" },
      { name: "diffjson", desc: "semantic diff of two JSON files via jq", usage: "diffjson <file-a> <file-b>", deps: "jq" },
      { name: "epoch", desc: "bidirectional Unix epoch and human datetime converter", usage: "epoch [epoch|date]" },
      { name: "retry", desc: "run command with exponential backoff retry", usage: "retry <max-attempts> <cmd> [args...]" },
    ],
  },
  {
    id: "jenkins",
    index: "12",
    name: "CI / JENKINS",
    sigil: "⟳",
    blurb: "Trigger, tail, inspect. Driven by JENKINS_URL, USER and TOKEN.",
    tools: [
      { name: "jenk-crumb", desc: "fetch a Jenkins CSRF crumb", usage: "jenk-crumb", deps: "jq" },
      { name: "jenk-build", desc: "trigger a Jenkins job build", usage: "jenk-build <job-name>" },
      { name: "jenk-logs", desc: "tail console output for a build", usage: "jenk-logs <job-name>" },
      { name: "jenk-jobs", desc: "list Jenkins job names", usage: "jenk-jobs", deps: "jq" },
    ],
  },
  {
    id: "meta",
    index: "13",
    name: "ORCHESTRATOR & HEALTH",
    sigil: "⌘",
    blurb: "Interactive terminal HUD, environment doctor, setup, benchmarks, and in-place updates.",
    tools: [
      { name: "sharmory", desc: "interactive HUD catalog, dispatcher, and runner", usage: "sharmory [list|help|run|doctor]" },
      { name: "sharmory-doctor", desc: "environment health check for shells and dependencies", usage: "sharmory doctor" },
      { name: "sharmory-setup", desc: "install optional CLI tools (fzf, jq, eza, tldr)", usage: "sharmory setup" },
      { name: "sharmory-bench", desc: "measure Sharmory source time in a clean shell", usage: "sharmory bench [n]" },
      { name: "sharmory-update", desc: "pull the latest armoury in place from GitHub", usage: "sharmory-update" },
    ],
  },
];

export const TOTAL_TOOLS = CATEGORIES.reduce((n, c) => n + c.tools.length, 0);

export const SHIPPED = TOTAL_TOOLS;

export const REPO = "https://github.com/hariharen9/sharmory";
